#ifndef WLR_VERSION_H
#define WLR_VERSION_H

#define WLR_VERSION_STR "0.17.4"

#define WLR_VERSION_MAJOR 0
#define WLR_VERSION_MINOR 17
#define WLR_VERSION_MICRO 4

#define WLR_VERSION_NUM ((WLR_VERSION_MAJOR << 16) | (WLR_VERSION_MINOR << 8) | WLR_VERSION_MICRO)

#endif
