/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define HAVE_EGL 1

#define HAVE_GBM_BO_GET_FD_FOR_PLANE 1

#define HAVE_XCB_ERRORS 0

#define ICONDIR "/usr/local/share/icons"

