const std = @import("std");
const posix = std.posix;

const log = std.log.scoped(.xorg);

var xorg_pid: posix.pid_t = 0;

/// zerocast-xorg: Privileged headless Xorg helper.
///
/// Spawns a headless Xorg server on a free display number using the NVIDIA
/// driver with UseDisplayDevice=none. Requires setuid root for VT access.
///
/// argv[1] = config file path (generated by the unprivileged daemon)
///
/// Protocol:
///   stdout: prints the display number (e.g. "99") when Xorg is ready
///   SIGTERM/SIGINT: kills Xorg and exits
///
/// The config file, resolution setup (xrandr), compositor (picom), and app
/// launch are all handled by the unprivileged daemon. This binary ONLY
/// manages the Xorg process lifecycle.
pub fn main() !void {
    const args = std.os.argv;
    if (args.len != 2) {
        log.err("usage: zerocast-xorg <config_path>", .{});
        std.process.exit(1);
    }

    const config_path = std.mem.span(args[1]);

    // When our parent (the daemon) dies, we should die too.
    // PR_SET_PDEATHSIG is cleared by setuid exec, so we re-set it here.
    const PR_SET_PDEATHSIG: i32 = 1;
    _ = std.os.linux.prctl(PR_SET_PDEATHSIG, @as(usize, @intCast(posix.SIG.TERM)), 0, 0, 0);
    // Race check: if parent already died during exec, we were reparented to init
    if (std.os.linux.getppid() == 1) {
        log.info("parent already exited, cleaning up", .{});
        std.process.exit(0);
    }

    // Find a free display number
    const display = findFreeDisplay() orelse {
        log.err("no free display number found (tried :10-:99)", .{});
        std.process.exit(2);
    };

    var display_arg: [4]u8 = undefined;
    const display_len = std.fmt.bufPrint(&display_arg, ":{d}", .{display}) catch unreachable;
    display_arg[display_len.len] = 0;

    var vt_arg: [8]u8 = undefined;
    const vt_num = currentVT();
    const vt_len = std.fmt.bufPrint(&vt_arg, "vt{d}", .{vt_num}) catch unreachable;
    vt_arg[vt_len.len] = 0;

    log.info("starting Xorg on :{d}, vt{d}", .{ display, vt_num });

    const pid = posix.fork() catch |err| {
        log.err("fork failed: {}", .{err});
        std.process.exit(3);
    };

    if (pid == 0) {
        // Child: ensure we run Xorg as root (inherited from setuid)
        // setuid gives us euid=0 but ruid=user. Xorg checks ruid on exec,
        // so set ruid=0 to preserve root across execve.
        // Check current euid
        log.info("child: uid={d} euid={d} gid={d} egid={d}", .{
            std.os.linux.getuid(), std.os.linux.geteuid(),
            std.os.linux.getgid(), std.os.linux.getegid(),
        });
        // Set all uid/gid to root. We have euid=0 from the setuid bit.
        // Use raw syscalls — glibc wrappers may fail due to capability checks.
        const SYS = std.os.linux.SYS;
        const setresgid_rc = std.os.linux.syscall3(SYS.setresgid, 0, 0, 0);
        if (setresgid_rc != 0) {
            log.err("setresgid failed: {d}", .{setresgid_rc});
            posix.exit(126);
        }
        const setresuid_rc = std.os.linux.syscall3(SYS.setresuid, 0, 0, 0);
        if (setresuid_rc != 0) {
            log.err("setresuid failed: {d}", .{setresuid_rc});
            posix.exit(126);
        }

        // TODO: redirect Xorg output in production

        const argv = [_:null]?[*:0]const u8{
            "/usr/lib/xorg/Xorg",
            @ptrCast(display_arg[0..display_len.len :0]),
            "-config",
            @ptrCast(config_path.ptr),
            "-noreset",
            "-novtswitch",
            "-sharevts",
            "-nolisten",
            "tcp",
            "-keeptty",
            @ptrCast(vt_arg[0..vt_len.len :0]),
        };

        const err = posix.execveZ(
            "/usr/lib/xorg/Xorg",
            &argv,
            @ptrCast(std.c.environ),
        );
        log.err("execve failed: {}", .{err});
        posix.exit(127);
    }

    xorg_pid = pid;

    // Install signal handlers to forward to Xorg
    const handler = posix.Sigaction{
        .handler = .{ .handler = handleSignal },
        .mask = std.mem.zeroes(posix.sigset_t),
        .flags = 0,
    };
    posix.sigaction(posix.SIG.TERM, &handler, null);
    posix.sigaction(posix.SIG.INT, &handler, null);

    // Wait for display socket to appear
    if (!waitForDisplay(display)) {
        log.err("Xorg failed to start (display :{d} socket not found)", .{display});
        posix.kill(pid, posix.SIG.TERM) catch {};
        _ = posix.waitpid(pid, 0);
        std.process.exit(4);
    }

    // Report display number to parent via stdout
    var out_buf: [64]u8 = undefined;
    var out = std.fs.File.stdout().writer(&out_buf);
    out.interface.print("{d}\n", .{display}) catch {};
    out.interface.flush() catch {};

    log.info("Xorg ready on :{d}", .{display});

    // Wait for Xorg to exit
    _ = posix.waitpid(pid, 0);
    log.info("Xorg stopped", .{});
}

fn handleSignal(_: c_int) callconv(.c) void {
    if (xorg_pid > 0) {
        posix.kill(xorg_pid, posix.SIG.TERM) catch {};
    }
}

fn findFreeDisplay() ?u8 {
    for (10..100) |d| {
        var socket_buf: [32]u8 = undefined;
        const socket_path = std.fmt.bufPrint(&socket_buf, "/tmp/.X11-unix/X{d}", .{d}) catch continue;
        socket_buf[socket_path.len] = 0;
        // Check if socket exists
        if (std.c.access(@ptrCast(socket_buf[0..socket_path.len :0]), 0) != 0) {
            return @intCast(d); // Free display
        }
        // Socket exists — check if the owning process is still alive
        if (isDisplayStale(d)) {
            log.info("cleaning up stale display :{d}", .{d});
            cleanupDisplay(d);
            return @intCast(d);
        }
    }
    return null;
}

/// Check if a display's lock file references a dead process.
fn isDisplayStale(display: usize) bool {
    var lock_buf: [32]u8 = undefined;
    const lock_path = std.fmt.bufPrint(&lock_buf, "/tmp/.X{d}-lock", .{display}) catch return false;

    const file = std.fs.openFileAbsolute(lock_path, .{}) catch return false;
    defer file.close();

    var pid_buf: [16]u8 = undefined;
    const n = file.read(&pid_buf) catch return false;
    const pid_str = std.mem.trim(u8, pid_buf[0..n], " \n\r");
    const pid = std.fmt.parseInt(posix.pid_t, pid_str, 10) catch return false;

    // If kill(pid, 0) fails with ESRCH, process doesn't exist
    posix.kill(pid, 0) catch |err| {
        if (err == error.ProcessNotFound) return true;
    };
    return false;
}

/// Remove stale lock file and socket for a display.
fn cleanupDisplay(display: usize) void {
    var lock_buf: [32]u8 = undefined;
    if (std.fmt.bufPrint(&lock_buf, "/tmp/.X{d}-lock", .{display})) |path| {
        std.fs.cwd().deleteFile(path) catch {};
    } else |_| {}

    var socket_buf: [32]u8 = undefined;
    if (std.fmt.bufPrint(&socket_buf, "/tmp/.X11-unix/X{d}", .{display})) |path| {
        std.fs.cwd().deleteFile(path) catch {};
    } else |_| {}
}

fn waitForDisplay(display: u8) bool {
    var path_buf: [32]u8 = undefined;
    const path = std.fmt.bufPrint(&path_buf, "/tmp/.X11-unix/X{d}", .{display}) catch return false;
    path_buf[path.len] = 0;

    // Poll for up to 30 seconds
    for (0..300) |_| {
        std.Thread.sleep(100 * std.time.ns_per_ms);
        if (std.c.access(@ptrCast(path_buf[0..path.len :0]), 0) == 0) {
            return true;
        }
    }
    return false;
}

fn currentVT() u8 {
    // Read active VT from /sys/class/tty/tty0/active
    var buf: [16]u8 = undefined;
    const file = std.fs.openFileAbsolute("/sys/class/tty/tty0/active", .{}) catch return 7;
    defer file.close();
    const n = file.read(&buf) catch return 7;
    const data = buf[0..n];
    // Format: "tty7\n"
    if (data.len >= 4 and std.mem.startsWith(u8, data, "tty")) {
        const num_str = std.mem.trimRight(u8, data[3..], "\n");
        return std.fmt.parseInt(u8, num_str, 10) catch 7;
    }
    return 7;
}
